# Generated by Django 3.2.6 on 2022-02-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0004_alter_avatar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
