# Generated by Django 2.0.1 on 2018-07-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20180706_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='room',
            field=models.CharField(choices=[('-', '-'), ('H. E. K Amissah Arthur Seminar Room', 'H. E. K Amissah Arthur Seminar Room'), ('The Foyer', 'The Foyer'), ('Prof. Ebenezer Oduro Owusu', 'Prof. Ebenezer Oduro Owusu'), ('Dr. Ernest Addison Seminar Room', 'Dr. Ernest Addison Seminar Room')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='talkschedule',
            name='room',
            field=models.CharField(choices=[('-', '-'), ('H. E. K Amissah Arthur Seminar Room', 'H. E. K Amissah Arthur Seminar Room'), ('The Foyer', 'The Foyer'), ('Prof. Ebenezer Oduro Owusu', 'Prof. Ebenezer Oduro Owusu'), ('Dr. Ernest Addison Seminar Room', 'Dr. Ernest Addison Seminar Room')], default='', max_length=100),
        ),
    ]
