# Generated by Django 3.2.6 on 2022-02-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20180707_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='room',
            field=models.CharField(choices=[('-', '-'), ('H. E. K Amissah Arthur Seminar Room', 'H. E. K Amissah Arthur Seminar Room'), ('The Foyer', 'The Foyer'), ('Prof. Ebenezer Oduro Owusu Seminar Room', 'Prof. Ebenezer Oduro Owusu Seminar Room'), ('Dr. Ernest Addison Seminar Room', 'Dr. Ernest Addison Seminar Room')], default='', max_length=100),
        ),
    ]
