# Generated by Django 3.2.6 on 2022-02-23 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(default='', max_length=30)),
                ('other_names', models.CharField(blank=True, default='', max_length=30)),
                ('surname', models.CharField(default='', max_length=30)),
                ('profession', models.CharField(default='', max_length=60)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile', serialize=False, to='auth.user')),
                ('biography', models.TextField(help_text='A little bio about yourself', max_length=500)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(default='', max_length=30)),
                ('contact_no', models.CharField(help_text="Please include your country code. eg.'233'", max_length=16, null=True)),
                ('github', models.CharField(blank=True, help_text="Please enter only the user name eg.'mawy7' ", max_length=32, null=True)),
                ('twitter', models.CharField(blank=True, default='', help_text="Please enter only the user name eg.'mawy_7' ", max_length=100, null=True)),
                ('linkedin', models.URLField(blank=True, default='', help_text='URL to your linkedin profile ', max_length=100, null=True)),
                ('website', models.URLField(blank=True, help_text='Your website/blog URL.', max_length=255, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=64, verbose_name='activation key')),
                ('activated', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'registration profile',
                'verbose_name_plural': 'registration profiles',
            },
        ),
        migrations.CreateModel(
            name='SupervisedRegistrationProfile',
            fields=[
                ('registrationprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.registrationprofile')),
            ],
            bases=('registration.registrationprofile',),
        ),
    ]
