# Generated by Django 2.0.1 on 2018-07-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0026_auto_20180706_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='talk_type',
            field=models.CharField(choices=[('-', '-'), ('Short Talk', 'Short Talk - 30 mins'), ('Long Talk', 'Long Talk - 45 mins'), ('Tutorial', 'Tutorial - 2 hours or more'), ('Keynote Speaker', 'Keynote Speaker')], max_length=20),
        ),
    ]
