# Generated by Django 3.2.6 on 2022-02-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0027_auto_20180706_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
